name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd C:\QuAero.WebApp & docker stop QuAero & docker rm QuAero & docker rmi QuAero & git pull & docker build . -t QuAero & docker run -p 3200:3000 -d -e DATABASE_URL=postgresql://QuAero:QuAero@host.docker.internal:5432/QuAero?schema=public --name QuAero --restart always QuAero
