name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: cd C:\ & git clone https://github.com/itupitsyn/QuAero.WebApp.git & cd C:\QuAero.WebApp & echo DATABASE_URL=${{ secrets.HOST_DATABASE_URL }} > .env & docker stop qu-aero & docker rm qu-aero & docker rmi qu-aero & docker build . -t qu-aero & docker run -p 3200:3000 -d -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name qu-aero --restart always qu-aero & cd C:\ & rmdir /S /Q QuAero.WebApp

